import { Metadata } from 'next'
import { SITE_NAME } from '@/lib/seo'

export const metadata: Metadata = {
  title: 'Disclaimer',
  description: `Disclosures about predictions, affiliate links, and data accuracy on ${SITE_NAME}.`,
  alternates: { canonical: '/disclaimer' },
}

export default function DisclaimerPage() {
  return (
    <section className="py-16">
      <div className="container max-w-3xl prose prose-sm">
        <h1>Disclaimer</h1>

        <h2>Predictions</h2>
        <p>
          Match predictions on this site are generated by a third-party statistical model
          (api-football's prediction engine), based on recent form, head-to-head history, and
          league statistics. Football is unpredictable — these percentages are a preview, not a
          guarantee, and should never be treated as financial or betting advice.
        </p>

        <h2>Not affiliated</h2>
        <p>
          {SITE_NAME} is an independent, fan-run information site. We are not affiliated with,
          endorsed by, or officially connected to the Premier League, any other football league
          featured on this site, FIFA, UEFA, or any individual club.
        </p>

        <h2>Affiliate and advertising disclosure</h2>
        <p>
          This site displays ads (via Google AdSense) and may include affiliate links — for
          example, on the Streams page. If you click an affiliate link and sign up or purchase
          something, we may earn a commission at no extra cost to you. This never changes the
          factual sports data (fixtures, injuries, scores) shown on the site.
        </p>

        <h2>Data accuracy</h2>
        <p>
          Fixture times, injury statuses, and scores are pulled from api-football.com and cached
          briefly for performance. Always double-check kickoff times and squad news against an
          official club or league source before making plans that depend on them.
        </p>
      </div>
    </section>
  )
}
